version: '3.1'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: magistrades-development
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
