version: '3.1'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: magistrades-development
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
